var searchData=
[
  ['—_20đọc_20điện_20áp_20supercap_20bằng_20adc_0',['Giai đoạn 3 — Đọc điện áp supercap bằng ADC',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md32',1,'']]],
  ['—_20đo_20dòng_1',['Task 10.4 — Đo dòng',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md87',1,'']]],
  ['—_20accelerometer_20basic_2',['Task 5.2 — Accelerometer basic',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md47',1,'']]],
  ['—_20action_20theo_20state_3',['Task 8.3 — Action theo state',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md70',1,'']]],
  ['—_20adaptive_20sampling_4',['Task 6.5 — Adaptive sampling',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md57',1,'']]],
  ['—_20ble_20wearable_20firmware_20trên_20stm32wb09_5',['Kế hoạch phát triển tiếp theo — BLE Wearable Firmware trên STM32WB09',['../md__b_l_e___wearable___firmware___next___plan.html',1,'']]],
  ['—_20bring_20up_20giao_20tiếp_6',['Task 5.1 — Bring-up giao tiếp',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md46',1,'']]],
  ['—_20cấu_20hình_20adc_7',['Task 3.1 — Cấu hình ADC',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md33',1,'']]],
  ['—_20chọn_20driver_20target_8',['Task 4.1 — Chọn driver target',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md40',1,'']]],
  ['—_20chuẩn_20hóa_20command_20protocol_9',['Task 1.3 — Chuẩn hóa command protocol',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md15',1,'']]],
  ['—_20driver_20bring_20up_10',['Task 6.1 — Driver bring-up',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md53',1,'']]],
  ['—_20ecg_20buffer_11',['Task 7.3 — ECG buffer',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md63',1,'']]],
  ['—_20ecg_20state_20riêng_12',['Task 7.2 — ECG state riêng',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md62',1,'']]],
  ['—_20ecg_20transport_20design_13',['Task 7.4 — ECG transport design',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md64',1,'']]],
  ['—_20fall_20candidate_20event_14',['Task 5.4 — Fall candidate event',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md49',1,'']]],
  ['—_20hoàn_20thiện_20ble_20gatt_20hiện_20tại_15',['Giai đoạn 1 — Hoàn thiện BLE GATT hiện tại',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md5',1,'']]],
  ['—_20hoàn_20thiện_20gatt_20read_20cho_20device_5fstatus_16',['Task 1.2 — Hoàn thiện GATT Read cho DEVICE_STATUS',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md11',1,'']]],
  ['—_20hoàn_20thiện_20gatt_20read_20cho_20sensor_5fdata_17',['Task 1.1 — Hoàn thiện GATT Read cho SENSOR_DATA',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md6',1,'']]],
  ['—_20hoàn_20thiện_20power_20manager_18',['Giai đoạn 8 — Hoàn thiện Power Manager',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md67',1,'']]],
  ['—_20hr_20extraction_19',['Task 6.3 — HR extraction',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md55',1,'']]],
  ['—_20hysteresis_20',['Task 8.2 — Hysteresis',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md69',1,'']]],
  ['—_20interrupt_20wake_20up_21',['Task 5.3 — Interrupt wake-up',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md48',1,'']]],
  ['—_20lưu_20flash_20an_20toàn_22',['Task 9.2 — Lưu flash an toàn',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md79',1,'']]],
  ['—_20low_20power_20thật_23',['Giai đoạn 10 — Low-power thật',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md83',1,'']]],
  ['—_20quy_20đổi_20adc_20sang_20điện_20áp_20thật_24',['Task 3.3 — Quy đổi ADC sang điện áp thật',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md35',1,'']]],
  ['—_20raw_20ppg_20streaming_20mode_25',['Task 6.2 — Raw PPG streaming mode',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md54',1,'']]],
  ['—_20reset_20counter_26',['Task 9.1 — Reset counter',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md78',1,'']]],
  ['—_20reset_20counter_20và_20persistence_27',['Giai đoạn 9 — Reset counter và persistence',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md77',1,'']]],
  ['—_20sleep_20policy_28',['Task 10.2 — Sleep policy',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md85',1,'']]],
  ['—_20spo2_29',['Task 6.4 — SpO2',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md56',1,'']]],
  ['—_20state_20machine_20năng_20lượng_30',['Task 8.1 — State machine năng lượng',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md68',1,'']]],
  ['—_20tách_20mock_20data_20khỏi_20ble_20logic_31',['Giai đoạn 2 — Tách mock data khỏi BLE logic',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md23',1,'']]],
  ['—_20tích_20hợp_20cảm_20biến_20nhiệt_20độ_20đầu_20tiên_32',['Giai đoạn 4 — Tích hợp cảm biến nhiệt độ đầu tiên',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md39',1,'']]],
  ['—_20tích_20hợp_20ecg_20thật_33',['Giai đoạn 7 — Tích hợp ECG thật',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md60',1,'']]],
  ['—_20tích_20hợp_20ppg_20hr_20spo2_34',['Giai đoạn 6 — Tích hợp PPG / HR / SpO2',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md52',1,'']]],
  ['—_20tích_20hợp_20st1vafe3bx_20phần_20imu_20trước_35',['Giai đoạn 5 — Tích hợp ST1VAFE3BX phần IMU trước',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md45',1,'']]],
  ['—_20tạo_20data_20model_20chung_36',['Task 2.1 — Tạo data model chung',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md24',1,'']]],
  ['—_20tạo_20driver_20voltage_20monitor_37',['Task 3.2 — Tạo driver voltage monitor',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md34',1,'']]],
  ['—_20tạo_20protocol_20version_38',['Task 1.4 — Tạo protocol version',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md21',1,'']]],
  ['—_20tạo_20sensormanager_20abstraction_39',['Task 2.2 — Tạo SensorManager abstraction',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md26',1,'']]],
  ['—_20tạo_20wearablestatemanager_40',['Task 2.3 — Tạo WearableStateManager',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md29',1,'']]],
  ['—_20tắt_20low_20power_20debug_20mode_41',['Task 10.1 — Tắt low-power debug mode',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md84',1,'']]],
  ['—_20test_20độc_20lập_42',['Task 4.3 — Test độc lập',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md42',1,'']]],
  ['—_20test_20matrix_43',['Giai đoạn 11 — Test matrix',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md90',1,'']]],
  ['—_20thêm_20lọc_20đơn_20giản_44',['Task 3.4 — Thêm lọc đơn giản',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md36',1,'']]],
  ['—_20vafe_20bring_20up_45',['Task 7.1 — vAFE bring-up',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md61',1,'']]],
  ['—_20viết_20driver_20cơ_20bản_46',['Task 4.2 — Viết driver cơ bản',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md41',1,'']]],
  ['—_20wake_20sources_47',['Task 10.3 — Wake sources',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md86',1,'']]],
  ['—_20wear_20leveling_20tối_20thiểu_48',['Task 9.3 — Wear leveling tối thiểu',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md80',1,'']]]
];
