var searchData=
[
  ['đề_20xuất_0',['Đề xuất',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md17',1,'']]],
  ['đọc_20điện_20áp_20supercap_20bằng_20adc_1',['Giai đoạn 3 — Đọc điện áp supercap bằng ADC',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md32',1,'']]],
  ['đo_20dòng_2',['Task 10.4 — Đo dòng',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md87',1,'']]],
  ['đơn_20giản_3',['Task 3.4 — Thêm lọc đơn giản',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md36',1,'']]],
  ['đầu_20tiên_4',['Giai đoạn 4 — Tích hợp cảm biến nhiệt độ đầu tiên',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md39',1,'']]],
  ['đề_20xuất_5',['Sprint tiếp theo đề xuất',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md99',1,'']]],
  ['đổi_20adc_20sang_20điện_20áp_20thật_6',['Task 3.3 — Quy đổi ADC sang điện áp thật',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md35',1,'']]],
  ['độ_20đầu_20tiên_7',['Giai đoạn 4 — Tích hợp cảm biến nhiệt độ đầu tiên',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md39',1,'']]],
  ['độc_20lập_8',['Task 4.3 — Test độc lập',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md42',1,'']]],
  ['điện_20áp_20supercap_20bằng_20adc_9',['Giai đoạn 3 — Đọc điện áp supercap bằng ADC',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md32',1,'']]],
  ['điện_20áp_20thật_10',['Task 3.3 — Quy đổi ADC sang điện áp thật',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md35',1,'']]],
  ['đoạn_201_20—_20hoàn_20thiện_20ble_20gatt_20hiện_20tại_11',['Giai đoạn 1 — Hoàn thiện BLE GATT hiện tại',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md5',1,'']]],
  ['đoạn_2010_20—_20low_20power_20thật_12',['Giai đoạn 10 — Low-power thật',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md83',1,'']]],
  ['đoạn_2011_20—_20test_20matrix_13',['Giai đoạn 11 — Test matrix',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md90',1,'']]],
  ['đoạn_202_20—_20tách_20mock_20data_20khỏi_20ble_20logic_14',['Giai đoạn 2 — Tách mock data khỏi BLE logic',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md23',1,'']]],
  ['đoạn_203_20—_20đọc_20điện_20áp_20supercap_20bằng_20adc_15',['Giai đoạn 3 — Đọc điện áp supercap bằng ADC',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md32',1,'']]],
  ['đoạn_204_20—_20tích_20hợp_20cảm_20biến_20nhiệt_20độ_20đầu_20tiên_16',['Giai đoạn 4 — Tích hợp cảm biến nhiệt độ đầu tiên',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md39',1,'']]],
  ['đoạn_205_20—_20tích_20hợp_20st1vafe3bx_20phần_20imu_20trước_17',['Giai đoạn 5 — Tích hợp ST1VAFE3BX phần IMU trước',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md45',1,'']]],
  ['đoạn_206_20—_20tích_20hợp_20ppg_20hr_20spo2_18',['Giai đoạn 6 — Tích hợp PPG / HR / SpO2',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md52',1,'']]],
  ['đoạn_207_20—_20tích_20hợp_20ecg_20thật_19',['Giai đoạn 7 — Tích hợp ECG thật',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md60',1,'']]],
  ['đoạn_208_20—_20hoàn_20thiện_20power_20manager_20',['Giai đoạn 8 — Hoàn thiện Power Manager',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md67',1,'']]],
  ['đoạn_209_20—_20reset_20counter_20và_20persistence_21',['Giai đoạn 9 — Reset counter và persistence',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md77',1,'']]],
  ['đoạn_20tiếp_20theo_22',['2. Mục tiêu giai đoạn tiếp theo',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md3',1,'']]]
];
