var searchData=
[
  ['tách_20mock_20data_20khỏi_20ble_20logic_0',['Giai đoạn 2 — Tách mock data khỏi BLE logic',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md23',1,'']]],
  ['tích_20hợp_20cảm_20biến_20nhiệt_20độ_20đầu_20tiên_1',['Giai đoạn 4 — Tích hợp cảm biến nhiệt độ đầu tiên',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md39',1,'']]],
  ['tích_20hợp_20ecg_20thật_2',['Giai đoạn 7 — Tích hợp ECG thật',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md60',1,'']]],
  ['tích_20hợp_20ppg_20hr_20spo2_3',['Giai đoạn 6 — Tích hợp PPG / HR / SpO2',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md52',1,'']]],
  ['tích_20hợp_20st1vafe3bx_20phần_20imu_20trước_4',['Giai đoạn 5 — Tích hợp ST1VAFE3BX phần IMU trước',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md45',1,'']]],
  ['tại_5',['tại',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md1',1,'1. Trạng thái hiện tại'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md5',1,'Giai đoạn 1 — Hoàn thiện BLE GATT hiện tại']]],
  ['tạo_20data_20model_20chung_6',['Task 2.1 — Tạo data model chung',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md24',1,'']]],
  ['tạo_20driver_20voltage_20monitor_7',['Task 3.2 — Tạo driver voltage monitor',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md34',1,'']]],
  ['tạo_20protocol_20version_8',['Task 1.4 — Tạo protocol version',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md21',1,'']]],
  ['tạo_20sensormanager_20abstraction_9',['Task 2.2 — Tạo SensorManager abstraction',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md26',1,'']]],
  ['tạo_20wearablestatemanager_10',['Task 2.3 — Tạo WearableStateManager',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md29',1,'']]],
  ['tắt_20low_20power_20debug_20mode_11',['Task 10.1 — Tắt low-power debug mode',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md84',1,'']]],
  ['tối_20thiểu_12',['Task 9.3 — Wear leveling tối thiểu',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md80',1,'']]],
  ['tự_20codex_20nên_20triển_20khai_13',['3. Thứ tự Codex nên triển khai',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md96',1,'']]],
  ['target_14',['Task 4.1 — Chọn driver target',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md40',1,'']]],
  ['task_201_201_20—_20hoàn_20thiện_20gatt_20read_20cho_20sensor_5fdata_15',['Task 1.1 — Hoàn thiện GATT Read cho SENSOR_DATA',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md6',1,'']]],
  ['task_201_202_20—_20hoàn_20thiện_20gatt_20read_20cho_20device_5fstatus_16',['Task 1.2 — Hoàn thiện GATT Read cho DEVICE_STATUS',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md11',1,'']]],
  ['task_201_203_20—_20chuẩn_20hóa_20command_20protocol_17',['Task 1.3 — Chuẩn hóa command protocol',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md15',1,'']]],
  ['task_201_204_20—_20tạo_20protocol_20version_18',['Task 1.4 — Tạo protocol version',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md21',1,'']]],
  ['task_2010_201_20—_20tắt_20low_20power_20debug_20mode_19',['Task 10.1 — Tắt low-power debug mode',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md84',1,'']]],
  ['task_2010_202_20—_20sleep_20policy_20',['Task 10.2 — Sleep policy',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md85',1,'']]],
  ['task_2010_203_20—_20wake_20sources_21',['Task 10.3 — Wake sources',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md86',1,'']]],
  ['task_2010_204_20—_20đo_20dòng_22',['Task 10.4 — Đo dòng',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md87',1,'']]],
  ['task_202_201_20—_20tạo_20data_20model_20chung_23',['Task 2.1 — Tạo data model chung',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md24',1,'']]],
  ['task_202_202_20—_20tạo_20sensormanager_20abstraction_24',['Task 2.2 — Tạo SensorManager abstraction',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md26',1,'']]],
  ['task_202_203_20—_20tạo_20wearablestatemanager_25',['Task 2.3 — Tạo WearableStateManager',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md29',1,'']]],
  ['task_203_201_20—_20cấu_20hình_20adc_26',['Task 3.1 — Cấu hình ADC',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md33',1,'']]],
  ['task_203_202_20—_20tạo_20driver_20voltage_20monitor_27',['Task 3.2 — Tạo driver voltage monitor',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md34',1,'']]],
  ['task_203_203_20—_20quy_20đổi_20adc_20sang_20điện_20áp_20thật_28',['Task 3.3 — Quy đổi ADC sang điện áp thật',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md35',1,'']]],
  ['task_203_204_20—_20thêm_20lọc_20đơn_20giản_29',['Task 3.4 — Thêm lọc đơn giản',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md36',1,'']]],
  ['task_204_201_20—_20chọn_20driver_20target_30',['Task 4.1 — Chọn driver target',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md40',1,'']]],
  ['task_204_202_20—_20viết_20driver_20cơ_20bản_31',['Task 4.2 — Viết driver cơ bản',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md41',1,'']]],
  ['task_204_203_20—_20test_20độc_20lập_32',['Task 4.3 — Test độc lập',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md42',1,'']]],
  ['task_205_201_20—_20bring_20up_20giao_20tiếp_33',['Task 5.1 — Bring-up giao tiếp',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md46',1,'']]],
  ['task_205_202_20—_20accelerometer_20basic_34',['Task 5.2 — Accelerometer basic',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md47',1,'']]],
  ['task_205_203_20—_20interrupt_20wake_20up_35',['Task 5.3 — Interrupt wake-up',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md48',1,'']]],
  ['task_205_204_20—_20fall_20candidate_20event_36',['Task 5.4 — Fall candidate event',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md49',1,'']]],
  ['task_206_201_20—_20driver_20bring_20up_37',['Task 6.1 — Driver bring-up',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md53',1,'']]],
  ['task_206_202_20—_20raw_20ppg_20streaming_20mode_38',['Task 6.2 — Raw PPG streaming mode',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md54',1,'']]],
  ['task_206_203_20—_20hr_20extraction_39',['Task 6.3 — HR extraction',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md55',1,'']]],
  ['task_206_204_20—_20spo2_40',['Task 6.4 — SpO2',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md56',1,'']]],
  ['task_206_205_20—_20adaptive_20sampling_41',['Task 6.5 — Adaptive sampling',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md57',1,'']]],
  ['task_207_201_20—_20vafe_20bring_20up_42',['Task 7.1 — vAFE bring-up',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md61',1,'']]],
  ['task_207_202_20—_20ecg_20state_20riêng_43',['Task 7.2 — ECG state riêng',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md62',1,'']]],
  ['task_207_203_20—_20ecg_20buffer_44',['Task 7.3 — ECG buffer',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md63',1,'']]],
  ['task_207_204_20—_20ecg_20transport_20design_45',['Task 7.4 — ECG transport design',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md64',1,'']]],
  ['task_208_201_20—_20state_20machine_20năng_20lượng_46',['Task 8.1 — State machine năng lượng',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md68',1,'']]],
  ['task_208_202_20—_20hysteresis_47',['Task 8.2 — Hysteresis',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md69',1,'']]],
  ['task_208_203_20—_20action_20theo_20state_48',['Task 8.3 — Action theo state',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md70',1,'']]],
  ['task_209_201_20—_20reset_20counter_49',['Task 9.1 — Reset counter',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md78',1,'']]],
  ['task_209_202_20—_20lưu_20flash_20an_20toàn_50',['Task 9.2 — Lưu flash an toàn',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md79',1,'']]],
  ['task_209_203_20—_20wear_20leveling_20tối_20thiểu_51',['Task 9.3 — Wear leveling tối thiểu',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md80',1,'']]],
  ['test_20độc_20lập_52',['Task 4.3 — Test độc lập',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md42',1,'']]],
  ['test_20matrix_53',['Giai đoạn 11 — Test matrix',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md90',1,'']]],
  ['thái_20hiện_20tại_54',['1. Trạng thái hiện tại',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md1',1,'']]],
  ['thêm_20lọc_20đơn_20giản_55',['Task 3.4 — Thêm lọc đơn giản',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md36',1,'']]],
  ['thật_56',['thật',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md83',1,'Giai đoạn 10 — Low-power thật'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md60',1,'Giai đoạn 7 — Tích hợp ECG thật'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md35',1,'Task 3.3 — Quy đổi ADC sang điện áp thật']]],
  ['thứ_20tự_20codex_20nên_20triển_20khai_57',['3. Thứ tự Codex nên triển khai',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md96',1,'']]],
  ['theo_58',['theo',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md3',1,'2. Mục tiêu giai đoạn tiếp theo'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md98',1,'4. Việc nên làm ngay tiếp theo'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md101',1,'5. Definition of Done cho sprint tiếp theo']]],
  ['theo_20đề_20xuất_59',['Sprint tiếp theo đề xuất',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md99',1,'']]],
  ['theo_20—_20ble_20wearable_20firmware_20trên_20stm32wb09_60',['Kế hoạch phát triển tiếp theo — BLE Wearable Firmware trên STM32WB09',['../md__b_l_e___wearable___firmware___next___plan.html',1,'']]],
  ['theo_20state_61',['Task 8.3 — Action theo state',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md70',1,'']]],
  ['thiểu_62',['Task 9.3 — Wear leveling tối thiểu',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md80',1,'']]],
  ['thiện_20ble_20gatt_20hiện_20tại_63',['Giai đoạn 1 — Hoàn thiện BLE GATT hiện tại',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md5',1,'']]],
  ['thiện_20gatt_20read_20cho_20device_5fstatus_64',['Task 1.2 — Hoàn thiện GATT Read cho DEVICE_STATUS',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md11',1,'']]],
  ['thiện_20gatt_20read_20cho_20sensor_5fdata_65',['Task 1.1 — Hoàn thiện GATT Read cho SENSOR_DATA',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md6',1,'']]],
  ['thiện_20power_20manager_66',['Giai đoạn 8 — Hoàn thiện Power Manager',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md67',1,'']]],
  ['tiên_67',['Giai đoạn 4 — Tích hợp cảm biến nhiệt độ đầu tiên',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md39',1,'']]],
  ['tiêu_68',['tiêu',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md7',1,'Mục tiêu'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md12',1,'Mục tiêu'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md16',1,'Mục tiêu']]],
  ['tiêu_20giai_20đoạn_20tiếp_20theo_69',['2. Mục tiêu giai đoạn tiếp theo',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md3',1,'']]],
  ['tiếp_70',['Task 5.1 — Bring-up giao tiếp',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md46',1,'']]],
  ['tiếp_20theo_71',['tiếp theo',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md3',1,'2. Mục tiêu giai đoạn tiếp theo'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md98',1,'4. Việc nên làm ngay tiếp theo'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md101',1,'5. Definition of Done cho sprint tiếp theo']]],
  ['tiếp_20theo_20đề_20xuất_72',['Sprint tiếp theo đề xuất',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md99',1,'']]],
  ['tiếp_20theo_20—_20ble_20wearable_20firmware_20trên_20stm32wb09_73',['Kế hoạch phát triển tiếp theo — BLE Wearable Firmware trên STM32WB09',['../md__b_l_e___wearable___firmware___next___plan.html',1,'']]],
  ['toàn_74',['Task 9.2 — Lưu flash an toàn',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md79',1,'']]],
  ['trên_20stm32wb09_75',['Kế hoạch phát triển tiếp theo — BLE Wearable Firmware trên STM32WB09',['../md__b_l_e___wearable___firmware___next___plan.html',1,'']]],
  ['trước_76',['Giai đoạn 5 — Tích hợp ST1VAFE3BX phần IMU trước',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md45',1,'']]],
  ['trạng_20thái_20hiện_20tại_77',['1. Trạng thái hiện tại',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md1',1,'']]],
  ['transport_20design_78',['Task 7.4 — ECG transport design',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md64',1,'']]],
  ['triển_20khai_79',['3. Thứ tự Codex nên triển khai',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md96',1,'']]],
  ['triển_20tiếp_20theo_20—_20ble_20wearable_20firmware_20trên_20stm32wb09_80',['Kế hoạch phát triển tiếp theo — BLE Wearable Firmware trên STM32WB09',['../md__b_l_e___wearable___firmware___next___plan.html',1,'']]]
];
