var searchData=
[
  ['abstraction_0',['Task 2.2 — Tạo SensorManager abstraction',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md26',1,'']]],
  ['accelerometer_20basic_1',['Task 5.2 — Accelerometer basic',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md47',1,'']]],
  ['acceptance_20criteria_2',['Acceptance criteria',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md9',1,'Acceptance criteria'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md13',1,'Acceptance criteria'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md19',1,'Acceptance criteria'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md27',1,'Acceptance criteria'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md30',1,'Acceptance criteria'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md37',1,'Acceptance criteria'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md43',1,'Acceptance criteria'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md50',1,'Acceptance criteria'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md58',1,'Acceptance criteria'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md65',1,'Acceptance criteria'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md75',1,'Acceptance criteria'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md81',1,'Acceptance criteria'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md88',1,'Acceptance criteria']]],
  ['action_20theo_20state_3',['Task 8.3 — Action theo state',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md70',1,'']]],
  ['adaptive_20sampling_4',['Task 6.5 — Adaptive sampling',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md57',1,'']]],
  ['adc_5',['ADC',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md32',1,'Giai đoạn 3 — Đọc điện áp supercap bằng ADC'],['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md33',1,'Task 3.1 — Cấu hình ADC']]],
  ['adc_20sang_20điện_20áp_20thật_6',['Task 3.3 — Quy đổi ADC sang điện áp thật',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md35',1,'']]],
  ['an_20toàn_7',['Task 9.2 — Lưu flash an toàn',['../md__b_l_e___wearable___firmware___next___plan.html#autotoc_md79',1,'']]]
];
